main/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import principal, mostrar_perfil
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('',auth_views.LoginView.as_view(),name='login'),
    path('admin/', admin.site.urls),
    path('principal/', principal, name='principal'),
    path('perfil/', mostrar_perfil, name='perfil'),
    path('contratos/', include('contratos.urls')),
    path('cargos/', include('cargos.urls')),
    path('personas/', include('personas.urls')),
    path('sstpersonas/', include('sstpersonas.urls')),
    path('sstempresa/', include('sstempresa.urls')),
    path('logout/', views.logout_usuario, name='logout'),
    path('recuperar-contrasena/', views.recuperar_contrasena, name='recuperar_contrasena'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personas/urls.py
from django.urls import path
from .views import personas, detalles_persona, editar_persona, crear_persona

urlpatterns = [
    path('', personas, name="personas"),
    path('personas/detalles/<int:persona_id>/', detalles_persona, name="detalles_persona"),
    path('personas/<int:id>/editar/', editar_persona, name='editar_persona'),
    path('personas/crear/', crear_persona, name="crear_persona"),
]

contratos/models.py
from django.db import models
from personas.models import Persona
from cargos.models import Cargo
from django.utils import timezone
import locale
from datetime import datetime

class Contrato(models.Model):
    razón_social = models.CharField(max_length=255, verbose_name='Razón social', default='DIGITAL BRIDGE COMMUNICATIONS')
    nit_empresa = models.CharField(max_length=20, default='901481430-5')
    nombre_representante_legal = models.CharField(max_length=255, default='Jonathan Cifuentes Cadena')
    cargo_representante_legal = models.CharField(max_length=255, default='Gerente')
    tipo_doc_representante_legal = models.CharField(max_length=20, verbose_name='Tipo doc representante legal', default='CC')
    numero_doc_representante_legal = models.CharField(max_length=20, verbose_name='Número doc representante legal', default='1016019519')
    lugar_expedicion_doc_representante_legal = models.CharField(max_length=255, verbose_name='Lugar expedición doc representante legal', default='Bogotá')
    celular_representante_legal = models.CharField(max_length=20, default='+57 320 8434390')
    correo_representante_legal = models.EmailField(max_length=255, verbose_name='Correo electrónico representante legal', default='jcifuentes@dbcw.com.co')
    ubicacion = models.CharField(max_length=255, verbose_name='Ubicación', default='Jenesano-Boyacá')
    direccion_notificacion_judicial= models.CharField(max_length=255, verbose_name='Dirección de notificación judicial', default='Calle 8 #3-42')

    empleado = models.ForeignKey(Persona, on_delete=models.CASCADE)

    TIPO_CONTRATO_CHOICES = [
        ('Contrato de Trabajo a Tiempo Completo - Término Fijo', 'Contrato de Trabajo a Tiempo Completo - Término Fijo'),
        ('Contrato de Trabajo a Tiempo Parcial - Término Fijo', 'Contrato de Trabajo a Tiempo Parcial - Término Fijo'),
        ('Contrato de Aprendizaje', 'Contrato de Aprendizaje'),
    ]
    ESTADO_CHOICES = [
        ('Activo', 'Activo'),
        ('Terminado', 'Terminado'),
        ('Vencido', 'Vencido'),
        ('Por vencer', 'Por vencer'),
        ('Liquidado', 'Liquidado'),
    ]
    cargo_contrato = models.ForeignKey(Cargo, on_delete=models.CASCADE)
    tipo_contrato = models.CharField(max_length=255, choices=TIPO_CONTRATO_CHOICES)
    salario = models.DecimalField(max_digits=10, decimal_places=0) 

    def formato_salario(self):
        locale.setlocale(locale.LC_ALL, '')
        salario_formateado = locale.currency(self.salario, grouping=True)
        return salario_formateado

    duracion_contrato = models.CharField(max_length=255)
    fecha_inicio = models.DateField()
    fecha_terminacion = models.DateField()
    fecha_pre_aviso = models.DateField()
    estado = models.CharField(max_length=100, choices=ESTADO_CHOICES, default='Activo')
    fecha_creacion_contrato = models.DateField(auto_now_add=True)  
    adjunto_contrato = models.FileField(upload_to='adjuntos_contratos/')
    fecha_carga_adjunto_contrato = models.DateField(auto_now_add=True)
    adjunto_preaviso = models.FileField(upload_to='adjuntos_preaviso/')
    dias_restantes = models.PositiveIntegerField(default=0, editable=False)
    consecutivo = models.PositiveIntegerField(unique=True, blank=True, null=True)

    def calcular_dias_restantes(self):
        hoy = datetime.now().date()
        dias_restantes = (self.fecha_terminacion - hoy).days
        return dias_restantes

    def actualizar_estado(self, save_instance=True):
        dias_restantes = self.calcular_dias_restantes()
        if dias_restantes < 0:
            nuevo_estado = 'Vencido'
        elif dias_restantes < 20:
            nuevo_estado = 'Por vencer'
        else:
            nuevo_estado = self.estado
        
        if self.estado != nuevo_estado:
            self.estado = nuevo_estado
            if save_instance:
                self.save(update_fields=['estado'])

    def save(self, *args, **kwargs):
        if self.consecutivo is None:
            ultimo_consecutivo = Contrato.objects.aggregate(models.Max('consecutivo'))['consecutivo__max']
            if ultimo_consecutivo is None:
                self.consecutivo = 140
            else:
                self.consecutivo = ultimo_consecutivo + 1
        self.actualizar_estado(save_instance=False)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.tipo_contrato} - Salario: ${self.salario:,.0f}"

personas/models.py
from django.db import models

class Persona(models.Model):
    nombre_persona = models.CharField(max_length=255)
    TIPO_DOCUMENTO_CHOICES = [
        ("CC", "Cédula de Ciudadanía"),
        ("CE", "Cédula de Extranjería"),
        ("P", "Pasaporte"),
    ]
    tipo_documento_persona = models.CharField(
        max_length=2, choices=TIPO_DOCUMENTO_CHOICES
    )
    numero_documento_persona = models.CharField(max_length=20)
    correo_persona = models.EmailField()
    celular_persona = models.CharField(max_length=20)
    direccion_residencia_persona = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre_persona  

sstpersonas/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from personas.models import Persona


TIPOS_DOCUMENTO_CHOICES = [
    ('Perfil sociodemográfico', 'Perfil sociodemográfico'),
    ('Análisis de puesto de trabajo', 'Análisis de puesto de trabajo'),
    ('Exámenes médicos', 'Exámenes médicos'),
    ('Otros', 'Otros'),
]

class PersonasSST(models.Model):
    persona_SST = models.ForeignKey(Persona, on_delete=models.CASCADE)

    tipo_documento = models.CharField(max_length=50, choices=TIPOS_DOCUMENTO_CHOICES, verbose_name='Tipo de Documento')
    nombre_documento = models.CharField(max_length=255, verbose_name='Nombre del Documento')
    archivo = models.FileField(upload_to='adjuntos_personaSST/')
    creado_por = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Creado por')
    fecha_creacion = models.DateTimeField(default=timezone.now, verbose_name='Fecha de Creación')

    def __str__(self):
        return self.nombre_persona

personas/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Row, Column, Submit
from .models import Persona

class PersonaForm(forms.ModelForm):
    nombre_persona = forms.CharField(label='Nombre Completo')
    tipo_documento_persona = forms.CharField(label='Tipo de Documento', widget=forms.Select(choices=Persona.TIPO_DOCUMENTO_CHOICES))
    numero_documento_persona = forms.CharField(label='Número de Documento')
    correo_persona = forms.EmailField(label='Correo Electrónico')
    celular_persona = forms.CharField(label='Celular')
    direccion_residencia_persona = forms.CharField(label='Dirección de Residencia')

    class Meta:
        model = Persona
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(PersonaForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Crear', style='background-color: #003594;'))
        self.helper.layout = Layout(
            Fieldset(
                'DATOS DE LA PERSONA',
                Row(
                    Column('nombre_persona', css_class='form-group col-md-4 mb-3'),
                    Column('tipo_documento_persona', css_class='form-group col-md-4 mb-3'),
                    Column('numero_documento_persona', css_class='form-group col-md-4 mb-3'),
                ),
                Row(
                    Column('correo_persona', css_class='form-group col-md-4 mb-3'),
                    Column('celular_persona', css_class='form-group col-md-4 mb-3'),
                    Column('direccion_residencia_persona', css_class='form-group col-md-4 mb-3'),
                ),
                css_class='seccion-container'
            ),
        )

class PersonaEditForm(forms.ModelForm):
    nombre_persona = forms.CharField(label='Nombre Completo')
    tipo_documento_persona = forms.CharField(label='Tipo de Documento', widget=forms.Select(choices=Persona.TIPO_DOCUMENTO_CHOICES))
    numero_documento_persona = forms.CharField(label='Número de Documento')
    correo_persona = forms.EmailField(label='Correo Electrónico')
    celular_persona = forms.CharField(label='Celular')
    direccion_residencia_persona = forms.CharField(label='Dirección de Residencia')

    class Meta:
        model = Persona
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(PersonaEditForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Guardar Cambios', style='background-color: #003594;'))
        self.helper.layout = Layout(
            Fieldset(
                'DATOS DE LA PERSONA',
                Row(
                    Column('nombre_persona', css_class='form-group col-md-4 mb-3'),
                    Column('tipo_documento_persona', css_class='form-group col-md-4 mb-3'),
                    Column('numero_documento_persona', css_class='form-group col-md-4 mb-3'),
                ),
                Row(
                    Column('correo_persona', css_class='form-group col-md-4 mb-3'),
                    Column('celular_persona', css_class='form-group col-md-4 mb-3'),
                    Column('direccion_residencia_persona', css_class='form-group col-md-4 mb-3'),
                ),
                css_class='seccion-container'
            ),
        )

main/views.py
# main/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.shortcuts import render
from django.db.models import Count
from django.utils import timezone
from personas.models import Persona
from sstpersonas.models import PersonasSST
from contratos.models import Contrato
import datetime
from django.shortcuts import render
from django.db.models.functions import ExtractMonth
from django.utils import timezone
from datetime import timedelta
import calendar

@login_required
def mostrar_perfil(request):
    usuario = request.user
    context = {
        'usuario': usuario
    }
    return render(request, 'perfil/perfil.html', context)

def recuperar_contrasena(request):
    return render(request, 'registration/olvide-contraseña.html')

def logout_usuario(request):
    logout(request)
    return redirect('login')


@login_required
def principal(request):
    # Conteo de personas
    total_personas = Persona.objects.count()

    # Conteo de contratos
    total_contratos = Contrato.objects.count()

    # Conteo de archivos adjuntos de personas SST
    total_archivos_adjuntos = PersonasSST.objects.count()

    # Obtener datos para el gráfico de contrataciones promedio por fechas
    contratos_por_mes = Contrato.objects \
        .annotate(mes_creacion=ExtractMonth('fecha_creacion_contrato')) \
        .values('mes_creacion') \
        .annotate(total=Count('id'))

    # Convertir los números de mes a nombres de mes
    for mes_data in contratos_por_mes:
        mes_num = mes_data['mes_creacion']
        mes_nombre = calendar.month_name[mes_num]
        mes_data['mes_nombre'] = mes_nombre

    # Contratos a punto de vencer
    contratos_a_punto_de_vencer = Contrato.objects.filter(fecha_terminacion__gte=timezone.now(), fecha_terminacion__lte=timezone.now() + timedelta(days=30)).count()

    context = {
        'total_personas': total_personas,
        'total_contratos': total_contratos,
        'total_archivos_adjuntos': total_archivos_adjuntos,
        'contratos_por_mes': contratos_por_mes,
        'contratos_a_punto_de_vencer': contratos_a_punto_de_vencer,
    }

    return render(request, 'Principal.html', context)
    

personas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Persona
from .forms import PersonaForm, PersonaEditForm
from django.contrib.auth.decorators import login_required

@login_required
def personas(request):
    personas_list = Persona.objects.all()
    return render(request, 'personas/personas.html', {'personas': personas_list})

@login_required
def crear_persona(request):
    if request.method == 'POST':
        form = PersonaForm(request.POST)
        if form.is_valid():
            persona = form.save()
            return redirect('detalles_persona', persona_id=persona.id)
    else:
        form = PersonaForm()
    
    return render(request, 'personas/crear_persona.html', {'form': form})

@login_required
def detalles_persona(request, persona_id):
    persona = get_object_or_404(Persona, id=persona_id)
    return render(request, 'personas/personaDetalles.html', {'persona': persona})

@login_required
def editar_persona(request, id):
    persona = Persona.objects.get(id=id)
    if request.method == 'POST':
        form = PersonaEditForm(request.POST, instance=persona)
        if form.is_valid():
            form.save()
            return redirect('detalles_persona', persona_id=persona.id)
    else:
        form = PersonaEditForm(instance=persona)
    
    return render(request, 'personas/editar_persona.html', {'form': form, 'persona': persona})

main/templates/personas/crear_persona.html
{% extends 'partials/body.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block contenido %}
  <title>CREAR PERSONA</title>

  <div class="contenedor" id="contenedor-contrato">
    <h2>CREAR PERSONA</h2>
    <br>

    <!-- Formulario de CREAR PERSONA -->
    <form method="post" action="{% url 'crear_persona' %}" enctype="multipart/form-data">
      {% csrf_token %}
      {% crispy form %}
    </form>
  </div>
  <br>
  <br>
{% endblock contenido %}

main/templates/personas/editar_persona.html
{% extends 'partials/body.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block contenido %}

<title>EDITAR PERSONA</title>

<div class="contenedor" id="contenedor-contrato">
  <h2>EDITAR PERSONA</h2>
    <br>

    <form method="post">
      {% csrf_token %}
      {% crispy form %}
    </form>
  </div>
{% endblock contenido %}

main/templates/personas/personaDetalles.html
{% extends 'partials/body.html' %}
{% load static %}

{% block contenido %}
<title>PERSONA DETALLES</title>

<div class="contenedor" id="contenedor-contrato">
  <h2>PERSONA</h2>
  <br>

  <!-- DATOS DE LA PERSONA -->
  <div class="seccion-container">
    <div class="row">
      <div class="col">
        <h3>DATOS DEL EMPLEADO</h3>
        <br>
        <div class="row mb-3">
          <div class="col-md-4">
            <label for="nombre_empleado" class="form-label">Nombre Completo:</label>
            <span id="nombre_empleado">{{ persona.nombre_persona }}</span>
          </div>
          <div class="col-md-4">
            <label for="tipo_documento_empleado" class="form-label">Tipo de documento de identidad:</label>
            <span id="tipo_documento_empleado">{{ persona.tipo_documento_persona }}</span>
          </div>
          <div class="col-md-4">
            <label for="numero_documento_empleado" class="form-label">Documento de identidad:</label>
            <span id="numero_documento_empleado">{{ persona.numero_documento_persona }}</span>
          </div>
        </div>

        <div class="row mb-3">
          <div class="col-md-4">
            <label for="correo_empleado" class="form-label">Correo electrónico:</label>
            <span id="correo_empleado">{{ persona.correo_persona }}</span>
          </div>
          <div class="col-md-4">
            <label for="celular_empleado" class="form-label">Celular:</label>
            <span id="celular_empleado">{{ persona.celular_persona }}</span>
          </div>
          <div class="col-md-4">
            <label for="direccion_residencia_empleado" class="form-label">Dirección de residencia:</label>
            <span id="direccion_residencia_empleado">{{ persona.direccion_residencia_persona }}</span>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- CONTRATOS -->
  <div class="seccion-container">
    <div class="row">
      <div class="col">
        <div class="d-flex justify-content-between align-items-center mb-3">
        <h3>CONTRATOS</h3>
        <a href="{% url 'crear_contrato' %}" class="btn btn-primary float-end" id="boton-crear">Crear Contrato</a>
        </div>
        <br>
        <div class="col-12 table-responsive">
          <table class="table table-striped table-hover table-bordered border-secondary table align-middle" id="tblcontratos">  
            <thead class="thead-dark align-middle">
              <tr id="tabla-header">
                <th scope="col" class="text-center">ID</th>
                <th scope="col" class="text-center">Tipo de Contrato</th>
                <th scope="col" class="text-center">Estado</th>
                <th scope="col" class="text-center">Fecha de Inicio</th>
                <th scope="col" class="text-center">Fecha de Finalización</th>
                <th scope="col" class="text-center">Ver Contrato</th>
              </tr>
            </thead>
            <tbody>
              {% for contrato in persona.contrato_set.all %}
              <tr>
                <td class="text-center">{{ contrato.id }}</td>
                <td class="text-center">{{ contrato.tipo_contrato }}</td>
                <td class="text-center">{{ contrato.estado }}</td>
                <td class="text-center">{{ contrato.fecha_inicio }}</td>
                <td class="text-center">{{ contrato.fecha_terminacion }}</td>
                <td class="text-center">
                  <a href="{% url 'detalles_contrato' contrato.id %}" class="btn btn-success" id="ver-mas">Ver Contrato</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <!-- DOCUMENTOS SST -->
  <div class="seccion-container">
    <div class="row">
      <div class="col">
        <div class="d-flex justify-content-between align-items-center mb-3">
        <h3>DOCUMENTOS SST</h3>
        <a href="{% url 'adjuntar_documentoSST' %}" class="btn btn-primary float-end" id="boton-crear">Adjuntar Documento SST</a>
        </div>
        <br>
        <div class="col-12 table-responsive">
          <table class="table table-striped table-hover table-bordered border-secondary table align-middle" id="tblpersonasSST">  
            <thead class="thead-dark align-middle">
              <tr id="tabla-header">
                <th scope="col" class="text-center">ID</th>
                <th scope="col" class="text-center">Tipo de Documento</th>
                <th scope="col" class="text-center">Nombre Documento</th>
                <th scope="col" class="text-center">Fecha de creación</th>
                <th scope="col" class="text-center">Creado por</th>
                <th scope="col" class="text-center">Ver Documento</th>
              </tr>
            </thead>
            <tbody>
              {% for personaSST in persona.personassst_set.all %}
              <tr>
                <td class="text-center">{{ personaSST.id }}</td>
                <td class="text-center">{{ personaSST.tipo_documento }}</td>
                <td class="text-center">{{ personaSST.nombre_documento }}</td>
                <td class="text-center">{{ personaSST.fecha_creacion }}</td>
                <td class="text-center">{{ personaSST.creado_por }}</td>
                <td class="text-center">
                  <a href="{% url 'detalles_personaSST' personaSST.id %}" class="btn btn-success" id="ver-mas">Ver Documento</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <!-- BOTONES -->
  <a href="{% url 'personas' %}" class="btn btn-primary" id="boton-volver">Volver</a>
  <a href="{% url 'editar_persona' persona.id %}" class="btn btn-primary float-end" id="boton-editar">Editar</a>
</div>
<br><br><br>
{% endblock contenido %}

main/templates/personas/personas.html
{% extends 'partials/body.html' %}
{% load static %}

{% block contenido %}
<title>PERSONAS</title>

<br>
<br>
<br>
<!-- Contenido de la página -->
<div class="container text-center bg-white text-dark border rounded" id="contenedor_general">
  <div class="row align-items-start">
      <div class="col-12">
        <br>
        <div class="d-flex justify-content-between align-items-center mb-3">
          <h2>Personas</h2>
          <a href="{% url 'crear_persona' %}" class="btn btn-primary float-end" id="boton-crear">Crear Persona</a>
        </div>
      </div>

      <div class="col-12">
        <div class="form-group row">
          <div class="col-md-2">
            <select id="filtroCampo" class="form-select">
              <option value="0">ID</option>
              <option value="1">Nombre</option>
              <option value="2">Tipo de Documento</option>
              <option value="3">Número de Documento</option>
              <option value="4">Correo Electrónico</option>
              <option value="5">Celular</option>
              <option value="6">Dirección de Residencia</option>
            </select>
          </div>
          <div class="col-md-2">
            <input type="text" id="busqueda" class="form-control" placeholder="Buscar...">
          </div>
        </div>
        <br>
      </div>

      <div class="col-12 table-responsive">
        <table class="table table-striped table-hover table-bordered border-secondary table align-middle" id="tblpersonas">  
          <thead class="thead-dark align-middle">
              <tr id="tabla-header">
              <th scope="col" class="text-center">ID</th>
              <th scope="col" class="text-center">Nombre</th>
              <th scope="col" class="text-center">Tipo de Documento</th>
              <th scope="col" class="text-center">Número de Documento</th>
              <th scope="col" class="text-center">Correo Electrónico</th>
              <th scope="col" class="text-center">Celular</th>
              <th scope="col" class="text-center">Dirección de Residencia</th>
              <th scope="col" class="text-center">Detalles</th>
            </tr>
          </thead>
          <tbody id="tblpersonas">
            {% for persona in personas %}
            <tr>
              <td class="text-center">{{ persona.id }}</td>
              <td class="text-center">{{ persona.nombre_persona }}</td>
              <td class="text-center">{{ persona.get_tipo_documento_persona_display }}</td>
              <td class="text-center">{{ persona.numero_documento_persona }}</td>
              <td class="text-center">{{ persona.correo_persona }}</td>
              <td class="text-center">{{ persona.celular_persona }}</td>
              <td class="text-center">{{ persona.direccion_residencia_persona }}</td>
              <td>
                <a href="{% url 'detalles_persona' persona.id %}"  class="btn btn-success" id="ver-mas">Ver Detalles</a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">

<script>
  $(document).ready(function() {
    $('#tblpersonas').DataTable({
      "pagingType": "simple_numbers", // Usamos el tipo de paginación simple con números de página
      "language": {
        "zeroRecords": "No se encontraron registros",
        "info": "Mostrando página _PAGE_ de _PAGES_",
        "infoEmpty": "No hay registros disponibles",
        "infoFiltered": "(filtrado de _MAX_ registros totales)",
        "paginate": {
          "first": "Primero",
          "last": "Último",
          "next": "Siguiente",
          "previous": "Anterior"
        },
        "search": "" // Desactiva el texto de búsqueda
      },
      "searching": true, // Habilitar la búsqueda
      "lengthChange": false // Desactiva el control de selección de registros por página
    });

    // Aplicar búsqueda por columna seleccionada
    $('#filtroCampo').change(function() {
      var columnIndex = $(this).val();
      $('#tblpersonas').DataTable().column(columnIndex).search($('#busqueda').val()).draw();
    });

    // Aplicar búsqueda al escribir en la barra de búsqueda
    $('#busqueda').on('keyup', function() {
      var columnIndex = $('#filtroCampo').val();
      $('#tblpersonas').DataTable().column(columnIndex).search(this.value).draw();
    });
  });
</script>
{% endblock contenido %}